### PR TITLE
Test Runs PHP-CS-Fixer

### PR DESCRIPTION
**Pull request by rcatlin**
* Run `make cs` in `test` target
* Run `composer update`
* Rename appropriate rules to newly renamed rules
* Remove deleted rules

### Notes
It's difficult to tell what rules were deleted or renamed. I'm attempting to get things passing. 

* `make cs` passes on Zeppelin

### CODE REVIEW

**Comment by kayladnls** [comment]
yaaaaaas

**Comment by kayladnls** [comment]
but now.. fix the thing that's breaking the thing.

**Comment by kayladnls** [comment]
looks good to me. :+1:

**Comment by rcatlin** [comment]
great-odins-raven-gif-anchorma-tlqj

**Comment by rcatlin** [comment]
Merging then tagging `v0.3.1`

**Comment by localheinz** [comment]
@kayladnls @rcatlin 

All of these problems could have been avoided - at least in part - by checking in `composer.lock`.!

**Comment by rcatlin** [comment]
All of these problems could have been avoided if we used exact version numbers or SHAs.

**Pull request merged**
